flat_fonctions-metiers.Rmd:
  path: dev/flat_fonctions-metiers.Rmd
  state: active
  R: R/stratopt.R
  tests: tests/testthat/test-stratopt.R
  vignettes: vignettes/go-further.Rmd
  inflate:
    flat_file: dev/flat_fonctions-metiers.Rmd
    vignette_name: Go further
    open_vignette: true
    check: true
    document: true
    overwrite: ask
