---
title: "flat_fonctions-metiers.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(shiny)

```

# Fonctions métiers de mon app
```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# stratopt
Cette fonction permet de récupérer les classes des sites crées en fonction de la stratification.
```{r function-stratopt}
#' Stratopt
#' Permet de récupérer les classes des sites
#'
#' @param data un dataframe
#'
#' @return une liste avec les 5 classes des sites
#' @importFrom stratification strata.cumrootf
#' @export
#'
stratopt<-function(data){

cum<-strata.cumrootf(x=data$Tonnages.DIM,n=5,Ls=5,alloc=c(0.5,0,0.5),nclass = 200)

class_opt<-numeric(dim(data)[1])

class_opt<-as.numeric(data$Tonnages.DIM<=cum$bh[1])+
  2*as.numeric(data$Tonnages.DIM>cum$bh[1]&data$Tonnages.DIM<=cum$bh[2])+
  3*as.numeric(data$Tonnages.DIM>cum$bh[2]&data$Tonnages.DIM<=cum$bh[3])+
  4*as.numeric(data$Tonnages.DIM>cum$bh[3]&data$Tonnages.DIM<=cum$bh[4])+
  5*as.numeric(data$Tonnages.DIM>cum$bh[4])

data_opt<-data.frame(data,class_opt)

list_opt<-list(classe1=data_opt$Site[data_opt$class_opt==1],
               classe2=data_opt$Site[data_opt$class_opt==2],
               classe3=data_opt$Site[data_opt$class_opt==3],
               classe4=data_opt$Site[data_opt$class_opt==4],
               classe5=data_opt$Site[data_opt$class_opt==5])

return(c(list_opt,bornes=cum$bh))
}


```

```{r examples-stratopt}
data("Tonnage")
stratopt(Tonnage)$classe1
```




```{r function-isOutreMer}
#' isOutreMer
#' permet de connaitre les sites situés en territoires outre mers
#'
#' @param data un dataframe 
#' @param classes la liste des classes des sites
#' @param nb le numero de la classe
#'
#' @return une liste de boolean, true si le site se situe en territoire outre mer
#' @export
#'
isOutreMer <- function(data,classes=NULL,nb=1){
  if(is.null(classes)){# cas général
    data[, "Region"] %in%
    c("La Reunion", "Guadeloupe ", "Martinique ", "Saint Martin", "Mayotte", "Guyane")
  }
  else{# cas d'une classe specifique
    data[data$Site %in% classes[[paste0("classe", nb)]], "Region"] %in%
      c("La Reunion", "Guadeloupe ", "Martinique ", "Saint Martin", "Mayotte", "Guyane")
  }
}
```

```{r examples-isOutreMer}
isOutreMer(Tonnage)
classes <- stratopt(Tonnage)
isOutreMer(Tonnage,classes,1)
```

```{r tests-isOutreMer}
test_that("isOutreMer works", {
  expect_equal(object = length(isOutreMer(Tonnage)), expected = nrow(Tonnage))
})
```


```{r function-use_darkmode}
#' Initialisation du mode sombre
#'
#' Charge les fichiers CSS et JS nécessaires pour le mode sombre.
#' @import shiny
#' @return pas de retour
#' @export
#' @author Deepanshu Bhalla
use_darkmode <- function() {
  tagList(
    tags$head(tags$script(src="https://cdn.jsdelivr.net/npm/darkmode-js@1.5.7/lib/darkmode-js.min.js")),
    tags$script("Shiny.addCustomMessageHandler('darkmode_enable', function(data) { eval(data.message) });"),
    tags$style(".darkmode-layer, .darkmode-toggle {z-index: 500;}")
  )
}
```

```{r examples-use_darkmode}
require(shiny)
vars <- setdiff(names(iris), "Species")
ui <- fluidPage(
  titlePanel("example App"), 
  # Setup
  use_darkmode(),
    sidebarPanel(
      selectInput('xcol', 'X Variable', vars),
     selectInput('ycol', 'Y Variable', vars, selected = vars[[2]]),
     numericInput('clusters', 'Cluster count', 3, min = 1, max = 9)
    )
)

```

```{r tests-use_darkmode}

```


```{r function-darkmode}
#' Activer le mode Sombre
#'
#' Permet d'activer le mode sombre avec un boutton
#'
#' @param session Session
#' @param bottom position basse du boutton
#' @param right position droite
#' @param left position gauche
#' @param time temps de l'animation
#' @param mixColor couleur 
#' @param backgroundColor couleur de fond
#' @param buttonColorDark couleur mode sombre
#' @param buttonColorLight couleur mode clair
#' @param saveInCookies si la valeur est "true", les préférences de l'utilisateur sont enregistrées dans un cookie. La valeur par défaut est false.
#' @param label boutton label pour utiliser le mode sombre
#' @param autoMatchOsTheme si la valeur est "true", le thème de couleur correspondra automatiquement aux préférences du système d'exploitation de l'utilisateur. 
#' @import jsonlite
#' @return pas de retour
#' @export
#'
#' @author Deepanshu Bhalla
#' 
darkmode <- function(session = getDefaultReactiveDomain(),
                     bottom = '32px',
                     right = '32px',
                     left = 'unset',
                     time = '0.5s',
                     mixColor = '#fff',
                     backgroundColor = '#fff',
                     buttonColorDark = '#100f2c',
                     buttonColorLight = '#fff',
                     saveInCookies = FALSE,
                     label = '🌓',
                     autoMatchOsTheme = TRUE) {

  options <- jsonlite::toJSON(list(
    bottom = bottom,
    right = right,
    left = left,
    time = time,
    mixColor = mixColor,
    backgroundColor = backgroundColor,
    buttonColorDark = buttonColorDark,
    buttonColorLight = buttonColorLight,
    saveInCookies = saveInCookies,
    label = label,
    autoMatchOsTheme = autoMatchOsTheme
  ), auto_unbox = TRUE)


  jscode0 <- paste0("const darkmode =  new Darkmode(",options, ");")
  jscode <- paste(jscode0, "darkmode.showWidget();")

  session$sendCustomMessage(
    type = "darkmode_enable", list(message = jscode)
  )

}
```

```{r examples-darkmode}
require(shiny)
vars <- setdiff(names(iris), "Species")
ui <- fluidPage(
  titlePanel("example App"), 
  # Setup
  use_darkmode(),
    sidebarPanel(
      selectInput('xcol', 'X Variable', vars),
     selectInput('ycol', 'Y Variable', vars, selected = vars[[2]]),
     numericInput('clusters', 'Cluster count', 3, min = 1, max = 9)
    )
)
server <- function(input,output,session){
  darkmode(label = '🌓')
  
}
```

```{r tests-darkmode}

```






```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_fonctions-metiers.Rmd", vignette_name = "Go further")
```

