# WARNING - Generated by {fusen} from dev/flat_fonctions-metiers.Rmd: do not edit by hand

proportions_compacteurs <- 
      Tonnage %>%
        mutate(Compacteur = ifelse(Compacteur == 1, "Avec Compacteur", "Sans Compacteur")) %>%
        group_by(Compacteur) %>%
        summarise(Count = dplyr::n()) %>%
        mutate(Proportion = Count / sum(Count))
test_that("pieCy returns a plotly object", {
  result <- pieCy(proportions_compacteurs)
  # Vérifier que le résultat est un objet plotly
  expect_true("plotly" == class(result)[1])
})
