# WARNING - Generated by {fusen} from dev/flat_fonctions-metiers.Rmd: do not edit by hand

test_that("isOutreMer works", {
  expect_equal(object = length(isOutreMer(Tonnage)), expected = nrow(Tonnage))
})
