# WARNING - Generated by {fusen} from dev/flat_fonctions-metiers.Rmd: do not edit by hand

r <- NULL
r$data <- Tonnage
r$classe <- stratopt(r$data)

data_copy <- Tonnage
data_copy$classe <- NA
data_copy$classe <- sapply(data_copy$Site, function(site) {
  for(i in 1:5){
    if (site %in% r$classe[[paste0("classe",i)]])
    return(i)
  }
  data_copy
})

totalTonnageParClasse <- summarise_data(data_copy,classe,r)

colorsM <- c("red", "green", "blue")
colorsR <- c("orange", "purple", "cyan")

totalTonnageParClasse <- summarise_data(data_copy,classe,r)
test_that("BarCy returns a plotly object", {
  result <- BarCy(viewType = "Tonnage par classe",
      colorsM = colorsM,
      colorsR = colorsR,
      proportions = NULL,
      totalTonnageParClasse = totalTonnageParClasse,
      totalTonnageParRegion = NULL,
      totalTonnageParMaison = NULL,
      sitesOutreMer = NULL)
  # Vérifier que le résultat est un objet plotly
  expect_true("plotly" == class(result)[1])
})
