# WARNING - Generated by {fusen} from dev/flat_fonctions-metiers.Rmd: do not edit by hand

#' BarCy
#' Créer et affiche des graphiques basés sur le type de vue sélectionné.
#'
#' @param viewType Le type de vue à générer, tel que "Proportion de Compacteurs par Classe".
#' @param colorsM Les couleurs à utiliser pour le graphique des Maisons Mères.
#' @param colorsR Les couleurs à utiliser pour le graphique des Régions.
#' @param proportions Les données sur la proportion de compacteurs par classe.
#' @param totalTonnageParClasse Les données sur le tonnage total par classe.
#' @param totalTonnageParRegion Les données sur le tonnage total par région.
#' @param totalTonnageParMaison Les données sur le tonnage total par maison mère.
#' @param sitesOutreMer Les données sur le nombre de sites en Outre-Mer par classe.
#' @import dplyr
#' @return Un graphique Plotly généré selon le type de vue sélectionné.
#' @export
#'
#' @examples
#' require(dplyr)
#' r <- NULL
#' r$data <- Tonnage
#' r$classe <- stratopt(r$data)
#'
#' data_copy <- Tonnage
#' data_copy$classe <- NA
#' data_copy$classe <- sapply(data_copy$Site, function(site) {
#'   for(i in 1:5){
#'     if (site %in% r$classe[[paste0("classe",i)]])
#'     return(i)
#'   }
#'   data_copy
#' })
#'
#' totalTonnageParClasse <- summarise_data(data_copy,classe,r)
#'
#' totalTonnageParRegion <- summarise_data(data_copy,Region,r)
#'
#' totalTonnageParMaison <- summarise_data(data_copy,Maison.Mere,r)
#'
#'
#' data_copy$IsOutreMer <- CyclamedSampleR::isOutreMer(data_copy)
#' sites_outre_mer <- summarise_data(data_copy %>% filter(IsOutreMer), classe, r)
#'
#' proportions <- 
#' data_copy %>%
#'   group_by(classe) %>%
#'   summarise(Count = dplyr::n(),
#'             ProportionCompacteur = mean(Compacteur),
#'             MinTonnage = min(Tonnages.DIM, na.rm = TRUE),
#'             MaxTonnage = max(Tonnages.DIM, na.rm = TRUE)) %>%
#'   mutate(
#'     class_name = dplyr::case_when(
#'       classe == 1 ~ paste("\u2264", r$classe$bornes1, " tonnes"),
#'       classe == 2 ~ paste("[", r$classe$bornes1, ";", r$classe$bornes2, ") tonnes"),
#'       classe == 3 ~ paste("[", r$classe$bornes2, ";", r$classe$bornes3, ") tonnes"),
#'       classe == 4 ~ paste("[", r$classe$bornes3, ";", r$classe$bornes4, ") tonnes"),
#'       classe == 5 ~ paste("\u2265", r$classe$bornes4, " tonnes")
#'     )
#'   )
#'
#' colorsM <- c("red", "green", "blue")
#' colorsR <- c("orange", "purple", "cyan")
#'
#' BarCy(viewType = "Tonnage par classe",
#'       colorsM = colorsM,
#'       colorsR = colorsR,
#'       proportions = proportions,
#'       totalTonnageParClasse = totalTonnageParClasse,
#'       totalTonnageParRegion = totalTonnageParRegion,
#'       totalTonnageParMaison = totalTonnageParMaison,
#'       sitesOutreMer = sites_outre_mer)

BarCy <- function(viewType, colorsM, colorsR, proportions, totalTonnageParClasse, totalTonnageParRegion, totalTonnageParMaison, sitesOutreMer) {
  switch(viewType,
         "Proportion de Compacteurs par Classe" = {
           plot_ly(data = proportions, x = ~classe, y = ~ProportionCompacteur, type = 'bar', name = 'ProportionCompacteur',
                   hovertext = ~paste('Intervalle de tonnage:', class_name, '<br>',
                                      'Nombre de Sites:', Count,
                                      '<br>Proportion de compacteur :', round(ProportionCompacteur, 3) * 100, "%"),
                   hoverinfo = 'text') %>%
             layout(margin = list(l = 50, r = 0, b = 5, t = 50), paper_bgcolor = '#ecf0f5', plot_bgcolor = '#ecf0f5', title = "Proportion de Compacteurs par Classe", xaxis = list(title = "Classe", categoryorder = "total ascending"), yaxis = list(title = "Proportion compacteur", showline = TRUE, showgrid = FALSE))
         },
         "Tonnage par classe" = {
           plot_ly(data = totalTonnageParClasse, x = ~classe, y = ~TotalTonnage, type = 'bar', name = 'Tonnage par classe',
                   hovertext = ~paste('Intervalle de tonnage:', class_name, '<br>',
                                      'Tonnage Total:', TotalTonnage, 'tonnes<br>',
                                      'Nombre de Sites:', NombreSites,
                                      '<br>Proportion du tonnage total :', round(Proportion, 3) * 100, "%"),
                   hoverinfo = 'text') %>%
             layout(margin = list(r = 0, b = 5, t = 50), paper_bgcolor = '#ecf0f5', plot_bgcolor = '#ecf0f5', title = "Tonnage par classe", xaxis = list(title = "Classe", categoryorder = "total ascending"),
                    yaxis = list(title = "Tonnages DIM tonnes", showgrid = FALSE, showline = TRUE))
         },
         "Tonnage par Régions" = {
           plot_ly(data = totalTonnageParRegion, x = ~TotalTonnage, y = ~Region, type = 'bar', orientation = 'h', name = 'Tonnage par Région',
                   marker = list(color = colorsR),
                   hovertext = ~paste('Région :', Region, '<br>',
                                      'Tonnage total :', TotalTonnage, '<br>',
                                      'Nombre de Sites:', NombreSites,
                                      '<br>Proportion du tonnage total:', round(Proportion, 3) * 100, "%"),
                   hoverinfo = 'text', source = "regionSelect") %>%
             layout(margin = list(r = 0, b = 5, t = 50), paper_bgcolor = '#ecf0f5', plot_bgcolor = '#ecf0f5', title = "Tonnage par Région", xaxis = list(title = "Tonnages DIM"),
                    yaxis = list(title = "Région", tickfont = list(size = 7), showgrid = FALSE, categoryorder = "total ascending"))
         },
         "Tonnage par Maison Mère" = {
           plot_ly(data = totalTonnageParMaison, x = ~TotalTonnage, y = ~Maison.Mere, type = 'bar', orientation = 'h',
                   marker = list(color = colorsM),
                   hovertext = ~paste('Maison mère :', Maison.Mere, '<br>',
                                      'Tonnage total :', TotalTonnage, '<br>',
                                      'Nombre de Sites:', NombreSites,
                                      '<br>Proportion de tonnage total :', round(Proportion, 3) * 100, "%"),
                   hoverinfo = 'text', source = "maisonSelect") %>%
             layout(margin = list(l = 100, r = 0, b = 5, t = 50), paper_bgcolor = '#ecf0f5', plot_bgcolor = '#ecf0f5',
                    title = "Tonnage par Maison Mère", xaxis = list(title = "Tonnages DIM"),
                    yaxis = list(title = "Maison Mère", tickfont = list(size = 7), showline = TRUE, showgrid = FALSE, categoryorder = "total ascending"))
         },
         "Nombre de Sites en Outre-Mer par Classe" = {
           plot_ly(data = sitesOutreMer, x = ~classe, y = ~NombreSites, type = 'bar', name = 'Nombre de Sites en Outre-Mer',
                   hovertext = ~paste('Intervalle de tonnage:', class_name, '<br>',
                                      'Total tonnage :', TotalTonnage, 'tonnes<br>',
                                      'Nombre de Sites:', NombreSites,
                                      '<br>Proportion de site:', round(Proportion, 3) * 100, "%"),
                   hoverinfo = 'text') %>%
             layout(margin = list(l = 50, r = 0, b = 5, t = 50), paper_bgcolor = '#ecf0f5', plot_bgcolor = '#ecf0f5', title = "Nombre de Sites en Outre-Mer par Classe", xaxis = list(title = "classe"),
                    yaxis = list(title = "site", showgrid = FALSE, showline = TRUE))
         }
  )
}

