# WARNING - Generated by {fusen} from dev/flat_fonctions-metiers.Rmd: do not edit by hand

#' BoxCy
#' permet d'afficher le graphique en boîte du tonnage en fonction des classes
#'
#' @param data un dataframe 
#' @param selected_region Région ou une valeur null
#' @param selected_maison Une maison mère une valeur null
#' @param selectedCompacteur booleen = "Avec Compacteur"/autre ou une valeur null
#' @import dplyr
#' @importFrom grDevices colorRampPalette
#' @importFrom stats quantile
#' @return Un graphique en boite du tonnage en fonction des classe
#' @export
#'
BoxCy <- function(data,selected_region,selected_maison,selectedCompacteur){
  palette_verte <- c("#00e000", "#00c100", "#00a200","#008300","#006400")
  
  #application filtre région /compacteur/maison
  if (!is.null(selected_region)) {
    data_filtered <- data %>% filter(Region == selected_region)
  }
  else if (!is.null(selected_maison)) {
    data_filtered <- data %>% filter(Maison.Mere == selected_maison)
  }
  else {
    data_filtered <- data
  }
  if(!is.null(selectedCompacteur)){
    data_filtered <- data_filtered %>% filter(Compacteur == ifelse(selectedCompacteur == "Avec Compacteur", 1, 0))
  }
  #Outliers pour la derniere classe
  last_class <- max(data_filtered$classe)
  data_last_class <- filter(data_filtered, classe == last_class)
  Q1 <- quantile(data_last_class$Tonnages.DIM, 0.25)
  Q3 <- quantile(data_last_class$Tonnages.DIM, 0.75)
  IQR <- Q3 - Q1
  upper_fence <- Q3 + 1.5 * IQR
  data_last_class$outlier <- ifelse(data_last_class$Tonnages.DIM > upper_fence, TRUE, FALSE)

  p <- plot_ly(data = data_filtered, y = ~Tonnages.DIM, x = ~factor(classe), type = "box",
               color = ~factor(classe), colors =  palette_verte)

  p <- add_trace(p, data = data_last_class[data_last_class$outlier == TRUE, ], y = ~Tonnages.DIM,
                 x = ~factor(classe), type = 'scatter', mode = 'markers',
                 marker = list(color = 'red', size = 5), hoverinfo = 'text',
                 text = ~paste("Site:", Site, "<br>Tonnage:", Tonnages.DIM)
  )
  
  #titre du graphique en fonction des filtres
  title_text <- "Boxplot du tonnage des classes"
  if (!is.null(selected_region)) {
    title_text <- paste(title_text, "\nDétails pour la région:", selected_region)
  } else if (!is.null(selected_maison)) {
    title_text <- paste(title_text, "\nDétails pour la maison mère:", selected_maison)
  }
  
  p <- layout(p,margin = list(l = 50, r = 0, b = 5, t = 50), title = title_text ,paper_bgcolor = '#ecf0f5',plot_bgcolor = '#ecf0f5',
              yaxis = list(title = "Tonnage",categoryorder = "total ascending",showline = TRUE,showgrid = FALSE,range = c(0, max(data$Tonnages.DIM)+10)), xaxis = list(title = "Classe",categoryorder = "array", categoryarray = c("1", "2", "3", "4", "5"))
  )
  p
}
