# WARNING - Generated by {fusen} from dev/flat_fonctions-metiers.Rmd: do not edit by hand

#' isOutreMer
#' permet de connaitre les sites situés en territoires outre mers
#'
#' @param data un dataframe 
#' @param classes la liste des classes des sites
#' @param nb le numero de la classe
#'
#' @return une liste de boolean, true si le site se situe en territoire outre mer
#' @export
#'
#' @examples
#' isOutreMer(Tonnage)
#' classes <- stratopt(Tonnage)
#' isOutreMer(Tonnage,classes,1)
isOutreMer <- function(data,classes=NULL,nb=1){
  if(is.null(classes)){# cas général
    data[, "Region"] %in%
    c("La Reunion", "Guadeloupe ", "Martinique ", "Saint Martin", "Mayotte", "Guyane")
  }
  else{# cas d'une classe specifique
    data[data$Site %in% classes[[paste0("classe", nb)]], "Region"] %in%
      c("La Reunion", "Guadeloupe ", "Martinique ", "Saint Martin", "Mayotte", "Guyane")
  }
}
