# WARNING - Generated by {fusen} from dev/flat_fonctions-metiers.Rmd: do not edit by hand

#' pieCy
#' permet d'afficher le graphique en secteur de proportion des compacteur
#'
#' @param proportions_compacteurs un dataframe 
#' @import magrittr
#' @return Un graphique pie plot en fonction de la proportion de compacteur
#' @export
#'
#' @examples
#' require(dplyr)
#' proportions_compacteurs <- 
#'       Tonnage %>%
#'         mutate(Compacteur = ifelse(Compacteur == 1, "Avec Compacteur", "Sans Compacteur")) %>%
#'         group_by(Compacteur) %>%
#'         summarise(Count = dplyr::n()) %>%
#'         mutate(Proportion = Count / sum(Count))
#'
#' pieCy(proportions_compacteurs)

pieCy <- function(proportions_compacteurs){
  plot_ly(proportions_compacteurs, labels = ~Compacteur, values = ~Count, type = 'pie', source = "pieChart",key = ~Compacteur, #Récupere les labels pour le filtre.
          hoverinfo = "text",
          text = ~Compacteur,
          hovertext = ~paste("<b> Compacteur :",Compacteur,"<br>",
                             "Nombre :",Count,"<br>",
                             "Pourcentage: ", round(Proportion,3)*100,"%"),
          textposition = 'inside',
          insidetextorientation = 'radial',
          marker = list(colors = c('Avec Compacteur' = 'red', 'Sans Compacteur' = 'blue'))
  ) %>%
    layout(title = 'Proportion de Compacteurs',paper_bgcolor = '#ecf0f5',
           margin = list(l = 0, r = 0, b = 5, t = 50),showlegend = FALSE )
}
