# WARNING - Generated by {fusen} from dev/flat_fonctions-metiers.Rmd: do not edit by hand

#' scatterCy
#' permet d'afficher le graphique de tonnage en fonction des rotations
#'
#' @param data un dataframe 
#' @param selected_maison Une maison mère une valeur null
#' @param selected_region Région ou une valeur null
#' @param selectedCompacteur booleen = "Avec Compacteur"/autre ou une valeur null
#' @import dplyr
#' @return Un graphique scatter plot en fonction des région/maison mère est la présence d'un compacteur
#' @export
#'
#' @examples
#' scatterCy(Tonnage,NULL,NULL,"Sans Compacteur")
scatterCy <- function(data,selected_maison,selected_region,selectedCompacteur){
  #ligne des moyennes 
  moyenne_DIM <- mean(data$Tonnages.DIM, na.rm = TRUE)
  moyenne_DIM_pas_compacteur <- mean(data$Tonnages.DIM[data$Compacteur == 0], na.rm = TRUE)
  moyenne_DIM_compacteur <- mean(data$Tonnages.DIM[data$Compacteur == 1], na.rm = TRUE)

  data_avec_compacteur <- data %>%
    filter(Compacteur == 1)

  data_sans_compacteur <- data %>%
    filter(Compacteur == 0)
  
  #application filtre région /compacteur/maison
  if (!is.null(selected_region)) {
    data_filteredA <- data_avec_compacteur %>% filter(Region == selected_region)
    data_filteredS <- data_sans_compacteur %>% filter(Region == selected_region)
  }
  else if (!is.null(selected_maison)) {
    data_filteredA <- data_avec_compacteur %>% filter(Maison.Mere == selected_maison)
    data_filteredS <- data_sans_compacteur %>% filter(Maison.Mere == selected_maison)
  }
  else {
    data_filteredA <- data_avec_compacteur
    data_filteredS <- data_sans_compacteur
  }
  if(!is.null(selectedCompacteur)){
    data_filteredA <- data_filteredA %>% filter(Compacteur == ifelse(selectedCompacteur == "Avec Compacteur", 1, 0))
    data_filteredS <- data_filteredS %>% filter(Compacteur == ifelse(selectedCompacteur == "Avec Compacteur", 1, 0))
  }
  #points avec compacteur
  p_scatter <- plot_ly() %>%
    add_trace(data = data_filteredA, x = ~Nbre.de.rotation, y = ~Tonnages.DIM,
              type = "scatter", mode = "markers",
              text = ~paste("Site:", data_filteredA$Site, "<br>Tonnages DIM:", data_filteredA$Tonnages.DIM,"<br>Compacteur: Avec"),
              hoverinfo = "text",
              marker = list(size = 4, color = 'red', symbol = 'circle'),
              name = "Avec Compacteur") %>%
    
      #points sans compacteur
    add_trace(data = data_filteredS, x = ~Nbre.de.rotation, y = ~Tonnages.DIM,
              text = ~paste("Site:", data_filteredS$Site, "<br>Tonnages DIM:", data_filteredS$Tonnages.DIM,"<br>Compacteur: Sans"),
              hoverinfo = "text",
              marker = list(size = 4, color = 'blue', symbol = 'circle'),
              name = "Sans Compacteur")
  #ligne (0,max(rotation)) besoin de 2 valeurs donc on donne deux fois la même pour obtenir une seul ligne
  p_scatter <- add_trace(p_scatter, x = c(0, max(data$Nbre.de.rotation, na.rm = TRUE)), y = rep(moyenne_DIM, 2),visible = 'legendonly',
                         type = "scatter", mode = "lines",
                         line = list(dash = 'dot', color = 'black', width = 2),
                         name = "Moyenne DIM",
                         hoverinfo = "none") %>%
    add_trace(x = c(0, max(data$Nbre.de.rotation, na.rm = TRUE)), y = rep(moyenne_DIM_compacteur, 2),visible = 'legendonly',
              type = "scatter", mode = "lines",
              line = list(dash = 'dot', color = 'red', width = 2),
              name = "Moyenne avec Compacteur",
              hoverinfo = "none") %>%
    add_trace(x = c(0, max(data$Nbre.de.rotation, na.rm = TRUE)), y = rep(moyenne_DIM_pas_compacteur, 2),visible = 'legendonly',
              type = "scatter", mode = "lines",
              line = list(dash = 'dot', color = 'blue', width = 2),
              name = "Moyenne sans Compacteur",
              hoverinfo = "none")

  title_text <- "Tonnages DIM en fonction du nombre de rotations"
  
#titre du graphique en fonction des filtres
  if (!is.null(selected_region)) {
    title_text <- paste(title_text, "\nDétails pour la région:", selected_region)
  } else if (!is.null(selected_maison)) {
    title_text <- paste(title_text, "\nDétails pour la maison mère:", selected_maison)
  }
   p_scatter <- layout(p_scatter,paper_bgcolor = '#ecf0f5',plot_bgcolor = '#ecf0f5',
                      title = title_text,
                      xaxis = list(title = "Nombres de rotation",range = c(0, max(data$Nbre.de.rotation)+10)),
                      yaxis = list(title = "Tonnage",range = c(0, max(data$Tonnages.DIM)+10)),
                      legend= list(
                        x = 1,            
                        xanchor = "left",
                        font = list(size = 8)
                      ),
                      margin = list(l = 50, r = 50, b = 70, t = 80))

  p_scatter
}
