# WARNING - Generated by {fusen} from dev/flat_fonctions-metiers.Rmd: do not edit by hand

#' summarise_data
#' permet de creer un  data frame tibble selon une variable group by
#'
#' @param data un dataframe 
#' @param group_var variable utilisé pour le group by
#' @param dataBorne dataframe contenant les bornes 
#' @import dplyr
#' @return Un data frame tibble.
#' @export
#'
#' @examples
#' r <- NULL
#' r$data <- Tonnage
#' r$classe <- stratopt(r$data)
#'
#' summarise_data(r$data,Region,r)
  
summarise_data <- function(data, group_var, dataBorne) {
  # Regroupement et résumé des données
  summarised_data <- data %>%
    group_by({{ group_var }}) %>%
    summarise(
      TotalTonnage = sum(Tonnages.DIM, na.rm = TRUE),
      NombreSites = dplyr::n(),
    ) %>%
    mutate(
      Proportion = TotalTonnage / sum(TotalTonnage)
    )

  if (dplyr::quo_name(dplyr::enquo(group_var)) == "classe") {
    summarised_data <- summarised_data %>%
      mutate(
        class_name = dplyr::case_when(
          classe == 1 ~ paste("\u2264", dataBorne$classe$bornes1, " tonnes"),
          classe == 2 ~ paste("[", dataBorne$classe$bornes1, ";", dataBorne$classe$bornes2, ") tonnes"),
          classe == 3 ~ paste("[", dataBorne$classe$bornes2, ";", dataBorne$classe$bornes3, ") tonnes"),
          classe == 4 ~ paste("[", dataBorne$classe$bornes3, ";", dataBorne$classe$bornes4, ") tonnes"),
          classe == 5 ~ paste("\u2265", dataBorne$classe$bornes4, " tonnes")
        )
      )
  }

  return(summarised_data)
}
